#!/usr/bin/env bash
#
# Regenerate requirements.lock from requirements.txt.
#
#   ./scripts/lock-deps.sh             # keep current pins, pick up new deps
#   ./scripts/lock-deps.sh --upgrade   # deliberately re-resolve to latest
#
# Resolution targets the Docker image (linux/x86_64, CPython 3.11), not the
# machine running this script, so a lock generated on macOS still installs in
# the container. By default the existing lock is fed back in as constraints:
# adding a dependency must not silently bump prophet or numpy underneath the
# forecast engines. Use --upgrade when you actually intend to move versions,
# and run the test suite afterwards.
set -euo pipefail

cd "$(dirname "$0")/.."

command -v uv >/dev/null 2>&1 || {
  echo "uv is required: https://docs.astral.sh/uv/getting-started/installation/" >&2
  exit 1
}

PLATFORM="x86_64-manylinux_2_28"
PY_VERSION="3.11"
ARGS=(--python-platform "$PLATFORM" --python-version "$PY_VERSION" --generate-hashes)

if [[ "${1:-}" == "--upgrade" ]]; then
  echo "Re-resolving to latest compatible versions (no constraints)."
else
  if [[ -f requirements.lock ]]; then
    CONSTRAINTS="$(mktemp -t rf-constraints)"
    trap 'rm -f "$CONSTRAINTS"' EXIT
    # Strip hashes and comments -> plain name==version constraint lines
    grep -oE '^[A-Za-z0-9._-]+==[A-Za-z0-9._+!-]+' requirements.lock > "$CONSTRAINTS"
    echo "Holding $(wc -l < "$CONSTRAINTS" | tr -d ' ') existing pins."
    ARGS+=(--constraint "$CONSTRAINTS")
  fi
fi

TMP_OUT="$(mktemp -t rf-lock)"
uv pip compile requirements.txt "${ARGS[@]}" --output-file "$TMP_OUT"

# uv records the constraints file path in `# via` comments; that path is a
# local temp dir, so strip it before the lock is committed.
python3 - "$TMP_OUT" <<'PY'
import re, sys, pathlib

src = pathlib.Path(sys.argv[1])
lines = [ln for ln in src.read_text().splitlines()
         if not re.match(r"^\s*#\s+-c\s+/", ln)]

cleaned = []
for i, ln in enumerate(lines):
    if ln.strip() == "# via":
        nxt = lines[i + 1] if i + 1 < len(lines) else ""
        if not re.match(r"^\s*#\s{3}\S", nxt):
            continue
    cleaned.append(ln)

header = """# Locked dependency set — DO NOT EDIT BY HAND.
#
# Regenerate with:  ./scripts/lock-deps.sh
#
# Resolved for the Docker target (linux/x86_64, CPython 3.11) and
# constrained to the versions the test suite is green against, so a
# rebuild cannot silently move prophet/statsmodels/numpy and change
# forecast output. Install with --require-hashes to enforce integrity."""

body = [ln for ln in cleaned
        if not ln.startswith("# This file was autogenerated")
        and not ln.startswith("#    uv pip compile")]

pathlib.Path("requirements.lock").write_text(
    header + "\n" + "\n".join(body).rstrip() + "\n"
)
PY

rm -f "$TMP_OUT"
echo "Wrote requirements.lock ($(grep -c '^[a-zA-Z0-9]' requirements.lock) packages)."
echo "Run the test suite before committing."
